--시퀀스
CREATE SEQUENCE SEQ_CHALLENGE
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE SEQ_CHALLENGE_COMMENT
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE SEQ_ATTACHMENT
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;


--챌린지 카테고리
CREATE TABLE CHALLENGE_CATEGORY (
    CATEGORY_NO   NUMBER         CONSTRAINT PK_CHALLENGE_CATEGORY PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(100)  CONSTRAINT NN_CHALLENGE_CATEGORY_NAME NOT NULL
);
COMMENT ON TABLE CHALLENGE_CATEGORY IS '챌린지 카테고리';
COMMENT ON COLUMN CHALLENGE_CATEGORY.CATEGORY_NO IS '카테고리 번호';
COMMENT ON COLUMN CHALLENGE_CATEGORY.CATEGORY_NAME IS '카테고리 이름';

-- 카테고리 데이터
INSERT INTO CHALLENGE_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (10, '운동');
INSERT INTO CHALLENGE_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (11, '달리기');
INSERT INTO CHALLENGE_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (12, '자전거');
INSERT INTO CHALLENGE_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (13, '헬스');
INSERT INTO CHALLENGE_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (14, '요가/필라테스');
INSERT INTO CHALLENGE_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (15, '등산');
INSERT INTO CHALLENGE_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (16, '기타');
INSERT INTO CHALLENGE_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (20, '자기계발');
INSERT INTO CHALLENGE_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (21, '공부');
INSERT INTO CHALLENGE_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (22, '독서');
INSERT INTO CHALLENGE_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (23, '재무관리');
INSERT INTO CHALLENGE_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (24, '피부관리');
INSERT INTO CHALLENGE_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (25, '다이어트');
INSERT INTO CHALLENGE_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (26, '기타');
INSERT INTO CHALLENGE_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (30, '라이프스타일');
INSERT INTO CHALLENGE_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (31, '식습관');
INSERT INTO CHALLENGE_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (32, '일기쓰기');
INSERT INTO CHALLENGE_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (33, '아침기상');
INSERT INTO CHALLENGE_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (34, '기타');
INSERT INTO CHALLENGE_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (40, '기타');
INSERT INTO CHALLENGE_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (41, '놀이방');
INSERT INTO CHALLENGE_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (42, '기부/봉사');
INSERT INTO CHALLENGE_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (43, '기타');

--챌린지
CREATE TABLE CHALLENGE (
    CHAL_NO           NUMBER        CONSTRAINT PK_CHALLENGE PRIMARY KEY,
    USER_NO           NUMBER        CONSTRAINT FK_CHALLENGE_USER REFERENCES USER_TABLE(USER_NO),
    CATEGORY_NO       NUMBER        CONSTRAINT FK_CHALLENGE_CATEGORY REFERENCES CHALLENGE_CATEGORY(CATEGORY_NO),
    TITLE             VARCHAR2(330) CONSTRAINT NN_CHALLENGE_TITLE NOT NULL,
    CONTENT           VARCHAR2(3300),
    VERIFY_CYCLE	  NUMBER(3),
    CREATE_DATE       TIMESTAMP     CONSTRAINT NN_CHALLENGE_CREATE_DATE NOT NULL,
    START_DATE        TIMESTAMP,
    END_DATE          TIMESTAMP,
    STATUS            VARCHAR2(1)   CONSTRAINT CK_CHALLENGE_STATUS CHECK (STATUS IN ('Y','N','D')),
    PICTURE_REQUIRED  VARCHAR2(1)   CONSTRAINT CK_CHALLENGE_STATUS CHECK (STATUS IN ('Y','N','D')),
    PICTURE_WATERMARK VARCHAR2(1)   CONSTRAINT CK_CHALLENGE_PICTURE_WATERMARK CHECK (PICTURE_REQUIRED IN ('D','F','N')),
    REPLY_REQUIRED    VARCHAR2(1)   CONSTRAINT CK_CHALLENGE_REPLY_REQUIRED CHECK (REPLY_REQUIRED IN ('Y','O','N'))
);
COMMENT ON TABLE CHALLENGE IS '챌린지';
COMMENT ON COLUMN CHALLENGE.CHAL_NO IS '챌린지 번호';
COMMENT ON COLUMN CHALLENGE.USER_NO IS '생성자';
COMMENT ON COLUMN CHALLENGE.CATEGORY_NO IS '카테고리 번호';
COMMENT ON COLUMN CHALLENGE.TITLE IS '챌린지 제목';
COMMENT ON COLUMN CHALLENGE.CONTENT IS '챌린지 내용';
COMMENT ON COLUMN CHALLENGE.VERIFY_CYCLE IS '인증 주기';
COMMENT ON COLUMN CHALLENGE.CREATE_DATE IS '챌린지 생성일시';
COMMENT ON COLUMN CHALLENGE.START_DATE IS '챌린지 시작일';
COMMENT ON COLUMN CHALLENGE.END_DATE IS '챌린지 종료일';
COMMENT ON COLUMN CHALLENGE.STATUS IS '상태(Y:활성화, N:종료됨, D:삭제됨)';
COMMENT ON COLUMN CHALLENGE.PICTURE_REQUIRED IS '사진 인증(Y:필수, O:선택, N:불가)';
COMMENT ON COLUMN CHALLENGE.PICTURE_WATERMARK IS '워터마크(D:디폴트 F:개인 N:없음)';
COMMENT ON COLUMN CHALLENGE.REPLY_REQUIRED IS '댓글(Y:필수, O:선택, N:불가)';

--챌린지 댓글
CREATE TABLE CHALLENGE_COMMENT (
    COMMENT_NO        NUMBER        CONSTRAINT PK_CHALLENGE_COMMENT PRIMARY KEY,
    USER_NO           NUMBER        CONSTRAINT FK_COMMENT_USER REFERENCES USER_TABLE(USER_NO),
    CHAL_NO           NUMBER        CONSTRAINT FK_COMMENT_CHALLENGE REFERENCES CHALLENGE(CHAL_NO),
    RECOMMENT_TARGET  NUMBER        CONSTRAINT FK_COMMENT_RECOMMENT REFERENCES CHALLENGE_COMMENT(COMMENT_NO),
    REPLY             VARCHAR2(3300),
    STATUS            VARCHAR2(1)   CONSTRAINT CK_COMMENT_STATUS CHECK (STATUS IN ('Y','N'))
);
COMMENT ON TABLE CHALLENGE_COMMENT IS '챌린지 댓글';
COMMENT ON COLUMN CHALLENGE_COMMENT.COMMENT_NO IS '댓글 번호';
COMMENT ON COLUMN CHALLENGE_COMMENT.USER_NO IS '작성자';
COMMENT ON COLUMN CHALLENGE_COMMENT.CHAL_NO IS '챌린지 번호';
COMMENT ON COLUMN CHALLENGE_COMMENT.RECOMMENT_TARGET IS '대댓글 대상 댓글번호';
COMMENT ON COLUMN CHALLENGE_COMMENT.REPLY IS '댓글 내용';
COMMENT ON COLUMN CHALLENGE_COMMENT.STATUS IS '상태(Y:활성, N:비활성)';

--첨부파일
CREATE TABLE ATTACHMENT (
    ATTACHMENT_NO   NUMBER        CONSTRAINT PK_ATTACHMENT PRIMARY KEY,
    CHAL_NO         NUMBER        CONSTRAINT FK_ATTACHMENT_CHALLENGE REFERENCES CHALLENGE(CHAL_NO),
    COMMENT_NO      NUMBER        CONSTRAINT FK_ATTACHMENT_COMMENT REFERENCES CHALLENGE_COMMENT(COMMENT_NO),
    FILE            BLOB          CONSTRAINT NN_ATTACHMENT_FILE NOT NULL,
    FILE_SIZE       NUMBER        CONSTRAINT NN_ATTACHMENT_FILE_SIZE NOT NULL,
    FILE_NAME       VARCHAR2(330) CONSTRAINT NN_ATTACHMENT_FILE_NAME NOT NULL,
    STATUS          VARCHAR2(1)   CONSTRAINT CK_ATTACHMENT_STATUS CHECK (STATUS IN ('Y','N')) DEFAULT 'Y'
);
COMMENT ON TABLE ATTACHMENT IS '첨부파일';
COMMENT ON COLUMN ATTACHMENT.ATTACHMENT_NO IS '첨부파일 번호';
COMMENT ON COLUMN ATTACHMENT.CHAL_NO IS '챌린지 번호';
COMMENT ON COLUMN ATTACHMENT.COMMENT_NO IS '댓글 번호';
COMMENT ON COLUMN ATTACHMENT.FILE IS '첨부파일(BLOB)';
COMMENT ON COLUMN ATTACHMENT.FILE_SIZE IS '파일 크기';
COMMENT ON COLUMN ATTACHMENT.FILE_NAME IS '파일 이름';
COMMENT ON COLUMN ATTACHMENT.STATUS IS '상태(Y:정상, N:삭제)';






commit;